apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  labels:
    type: nfs
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi