---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-dev-deployment
  namespace: mariadb-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mariadb-dev
  template:
    metadata:
      labels:
        component: mariadb-dev
    spec:
      containers:
        - name: mariadb-dev
          image: mariadb
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "L0g!tech"
            - name: MYSQL_ROOT_HOST
              value: "%"